# Generated by Django 5.1 on 2024-09-14 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='user_userprofile',
        ),
    ]
