# Generated by Django 5.1.1 on 2024-10-07 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0003_userprofile_cofirm_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='cofirm_password',
            new_name='confirm_password',
        ),
    ]
