# Generated by Django 5.1.1 on 2024-10-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0005_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
