# Generated by Django 5.1.1 on 2024-10-08 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0006_product_pname_product_price_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='file',
        ),
    ]
