# Generated by Django 5.1.1 on 2024-10-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=30, null=True)),
                ('price', models.CharField(max_length=50, null=True)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
